language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: COMPILER=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5

    - os: linux
      compiler: clang
      env: COMPILER=clang++

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env: COMPILER=clang++-3.5

script:
  - echo "script started"
  - dpkg --list | grep compile
  - cd ./stdex
  - chmod +x ./build_lib.sh
  - ./build_lib.sh
  - cd ..
  - chmod +x ./build_tests.sh
  - ./build_tests.sh
  - chmod +x ./run_tests.sh
  - ./run_tests.sh

after_success:
  - chmod +x ./merge_to_work.sh
  - ./merge_to_work.sh
  - git remote
  - git config user.email 0oktonion0@gmail.com
  - git config user.name oktonion
  - git push "https://${TRAVIS_SECURE_TOKEN_NAME}@$github.com/oktonion/stdex.git" work
#make CXX=$COMPILER -j3